### ISSUE TITLE
程序报错找不到leap.sec

### ISSUE THREAD

**Issue by liusheng2020** [lizhengnss/POSGO#2]
(base) ls@ls-ThinkPad:~/下载/posgo240430/POSGO/build_release$ ./POSGO -C ../conf/spp_kpl_gold.ini -S GREC -M SPP -L 1
15:28:25: *ReadLeapSecond: Leap second file doesn't exit, Please check: /mnt/hgfs/VirtualFile/posgo_ws/src/POSGO/tables/leap.sec

事实上，整个/mnt都是空的。/但发现POSGO/tables文件夹下有leap.sec文件。需要手动移动吗
![image](https://github.com/lizhengnss/POSGO/assets/74414558/f53847ac-8c35-4fa0-88f3-682d23ef6eed)

**Comment by lizhengnss** [comment]
你好，可以在配置文件中对跳秒文件的路径进行配置：
File-Leapsec         = 更换为你的路径
